<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand active" href="../../assistant-dash/main.php">iRobot</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="create-user.php">Create User</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="../../assistant-dash/tour/tour-dash.php">Tours & Locations Dashboard</a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="../../assistant-dash/bookings.php">Bookings</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="../../logout.php"><span class="glyphicon glyphicon-user"></span> logout</a></li>
    </ul>
  </div>
</nav>
