<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">I-Robot</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="../../assistant-dash/tour/tour-dash.php">Tour Dashboard</a></li>
      <li><a href="#"></a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="../../logout.php"><span class="glyphicon glyphicon-user"></span> logout</a></li>
    </ul>
  </div>
</nav>
