<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="main.php">I-Robot</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="../users-dash/booked-tours.php">Booked Tours</a></li>
      <li><a href="#"></a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="../users-dash/account-details.php">Account</a></li>
      <li><a href="#"></a></li>
    </ul>

    <ul class="nav navbar-nav">
      <li><a href="../tours.php">Tours</a></li>
      <li><a href="#"></a></li>
    </ul>
    <ul class="nav navbar-nav">
      <li><a href="../locations/locations.php">Locations</a></li>
      <li><a href="#"></a></li>
    </ul>

    <ul class="nav navbar-nav navbar-right">
      <li><a href="../../logout.php"><span class="glyphicon glyphicon-user"></span> logout</a></li>
    </ul>
  </div>
</nav>
